[package]
name = "amethyst_tools"
version = "0.4.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "Game development tools for the Amethyst engine"
keywords = ["game", "engine", "tool", "editor", "amethyst"]

repository = "https://github.com/ebkalderon/amethyst_tools"

readme = "README.md"
license = "GPL-3.0"

[[bin]]
name = "amethyst"
path = "src/cli/main.rs"

[dependencies]
clap = { version = "2", features = ["unstable"] }
zip = { version = "0.1.16", default-features = false }
yaml-rust = "0.3.2"
walkdir = "0.1"
toml = "0.1"
